// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsHup70X2ggKKbHSv9sLIP0odpExwVGBc',
    appId: '1:1074929957492:web:05ebea86da6f1b5eccef21',
    messagingSenderId: '1074929957492',
    projectId: 'varadifi-app',
    authDomain: 'varadifi-app.firebaseapp.com',
    storageBucket: 'varadifi-app.firebasestorage.app',
    measurementId: 'G-V9KZZCGWFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Pq_vZhPvH-E1fSUd11CTjaJr-uraxBU',
    appId: '1:1074929957492:android:a90edc39910d79aeccef21',
    messagingSenderId: '1074929957492',
    projectId: 'varadifi-app',
    storageBucket: 'varadifi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4QwixN_9MCs-GnDOjFtPaMSZpIZ83uSA',
    appId: '1:1074929957492:ios:3051703f6d63564bccef21',
    messagingSenderId: '1074929957492',
    projectId: 'varadifi-app',
    storageBucket: 'varadifi-app.firebasestorage.app',
    iosBundleId: 'com.example.varadifiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4QwixN_9MCs-GnDOjFtPaMSZpIZ83uSA',
    appId: '1:1074929957492:ios:3051703f6d63564bccef21',
    messagingSenderId: '1074929957492',
    projectId: 'varadifi-app',
    storageBucket: 'varadifi-app.firebasestorage.app',
    iosBundleId: 'com.example.varadifiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsHup70X2ggKKbHSv9sLIP0odpExwVGBc',
    appId: '1:1074929957492:web:e41c83b496ab497dccef21',
    messagingSenderId: '1074929957492',
    projectId: 'varadifi-app',
    authDomain: 'varadifi-app.firebaseapp.com',
    storageBucket: 'varadifi-app.firebasestorage.app',
    measurementId: 'G-SBJ06DTFG3',
  );

}